---
- hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    plex_download_url: 'https://downloads.plex.tv/plex-media-server/0.9.11.7.803-87d0708/plexmediaserver_0.9.11.7.803-87d0708_i386.deb' 
    deluged_user: media
    couchpotato_user: media
    sickbeard_user: media
    htpc_manager_user: media

  roles:
    - plex
    - deluge
    - couchpotato
    - sickbeard
    - htpc-manager

