---
deluge_enabled: True

# Deluge Daemon Path
deluged_path: /opt/deluged
deluged_user: debian-deluged

# Default download locations
media_path: /mnt/media
downloads_path: "{{ media_path }}/downloads"
deluged_incomplete: "{{ downloads_path }}/incomplete/deluged"

# Required for nzbtomedia processing
process_path: "{{ downloads_path }}/incomplete/process"  

deluged_localclient_password: "{{ lookup('password', '/opt/deluged/generated_password chars=ascii_letters') }}"

deluged_host: "{{ ansible_default_ipv4.address }}"
deluged_port: 8112
