- name: Enable UFW with default deny
  ufw: state=enabled policy=deny

- name: Enable logging
  ufw: logging=on

- name: Allow SSH
  ufw: rule=allow name=ssh

- name: Allow www
  ufw: rule=allow name=www
